// rmii2mii.v

// Generated using ACDS version 24.1 1077

`timescale 1 ps / 1 ps
module mii2rmii (
		input  wire       ena_10,      //                    MACSPEED.ena_10
		input  wire       RefClk,      //                  clock_sink.clk
		input  wire       m_tx_en,     //               mii_interface.mii_tx_en
		input  wire [3:0] m_tx_d,      //                            .mii_tx_d
		input  wire       m_tx_err,    //                            .mii_tx_err
		output wire       m_rx_en,     //                            .mii_rx_dv
		output wire [3:0] m_rx_d,      //                            .mii_rx_d
		output wire       m_rx_err,    //                            .mii_rx_err
		output wire       m_rx_crs,    //                            .mii_crs
		output wire       m_rx_col,    //                            .mii_col
		output wire       rx_clk,      // pcs_mac_rx_clock_connection.clk
		output wire       tx_clk,      // pcs_mac_tx_clock_connection.clk
		input  wire       Rstn,        //                  reset_sink.reset_n
		input  wire       rmii_crs_dv, //              rmii_interface.crs
		input  wire [1:0] rmii_rx_d,   //                            .rxdata
		input  wire       rmii_rx_err, //                            .rxerror
		output wire       rmii_tx_en,  //                            .txenable
		output wire [1:0] rmii_tx_d    //                            .txdata
	);

	intel_fpga_mii2rmii #(
		.RX_FIXED_THROUGHPUT (1),
		.MBPS                (1),
		.MAC_SPEED           (1)
	) fpga_mii2rmii_0 (
		.RefClk      (RefClk),      //                  clock_sink.clk
		.Rstn        (Rstn),        //                  reset_sink.reset_n
		.m_tx_en     (m_tx_en),     //               mii_interface.mii_tx_en
		.m_tx_d      (m_tx_d),      //                            .mii_tx_d
		.m_tx_err    (m_tx_err),    //                            .mii_tx_err
		.m_rx_en     (m_rx_en),     //                            .mii_rx_dv
		.m_rx_d      (m_rx_d),      //                            .mii_rx_d
		.m_rx_err    (m_rx_err),    //                            .mii_rx_err
		.m_rx_crs    (m_rx_crs),    //                            .mii_crs
		.m_rx_col    (m_rx_col),    //                            .mii_col
		.rmii_crs_dv (rmii_crs_dv), //              rmii_interface.crs
		.rmii_rx_d   (rmii_rx_d),   //                            .rxdata
		.rmii_rx_err (rmii_rx_err), //                            .rxerror
		.rmii_tx_en  (rmii_tx_en),  //                            .txenable
		.rmii_tx_d   (rmii_tx_d),   //                            .txdata
		.ena_10      (ena_10),      //                    MACSPEED.ena_10
		.rx_clk      (rx_clk),      // pcs_mac_rx_clock_connection.clk
		.tx_clk      (tx_clk)       // pcs_mac_tx_clock_connection.clk
	);

endmodule
